Lesson 12 oauth
Arkweid/qanda pull request #14
Opened 2016-10-03 07:27 UTC by Arkweid

2016-10-03 19:09 UTC, palkan requested changes
Внимательно читаем задание: 

> При аутентификации через Twitter запрашивать email пользователя дополнительно (только в первый раз).

Твиттер не отдает email при OAuth аутентификации, его нужно запрашивать отдельно.

2016-10-03 19:09 UTC, palkan commented on app/controllers/answers_controller.rb
> +  # after_action :publish_answer, only: [:create]
хм 🤔

2016-10-03 19:14 UTC, Arkweid commented on app/controllers/answers_controller.rb
> +  # after_action :publish_answer, only: [:create]
Твиттер спокойно отдает емейл, как и фейсбук. Возможно раньше не отдавал.
http://connect.thinknetica.com/t/zanyatie-12-oauth-i-autentifikacziya-cherez-soczialnye-seti-voprosy-i-kommentarii/467/84?u=a.a.abroskin

2016-10-04 07:03 UTC, palkan commented on app/controllers/answers_controller.rb
> +  # after_action :publish_answer, only: [:create]
У нас есть конкретная задача – обрабатывать сценарий, при котором email не возвращается.
Такая ситуация может быть и с Facebook или VK, в котором пользователь может регистрироваться без email, а только по номеру телефона.

Так что функционал этот все равно нужен.

2016-10-04 10:58 UTC, Arkweid commented on app/controllers/answers_controller.rb
> +  # after_action :publish_answer, only: [:create]
Твиттер запрашивает у пользователя же, хочет ли он отдать емейл? Если не хочет, тогда мы просто не авторизуем пользователя.

2016-10-04 12:36 UTC, Arkweid commented on app/controllers/answers_controller.rb
> +  # after_action :publish_answer, only: [:create]
Сделал один из вариантов, который предлагался в скринкасте. Сгенерировал емейл для пользователя, который его не отдает.

2016-10-05 08:12 UTC, merged