Lesson 17 background work
Arkweid/qanda pull request #19
Opened 2016-10-14 11:33 UTC by Arkweid

2016-10-14 16:07 UTC, palkan requested changes

2016-10-14 16:07 UTC, palkan commented on app/models/question.rb
> +  scope :from_yesterday, -> { where(created_at: (Time.now - 1.day).beginning_of_day.utc..(Time.now - 1.day).end_of_day.utc) }
Во-первых, зачем `utc`?

Во-вторых, в `where` можно передать Range: `where(created_at: 1.day.ago.all_day)`.

2016-10-14 16:07 UTC, palkan commented on app/models/user.rb
> +    subscriptions.where(question: question).delete_all if subscribed?(question)
Можно и не проверять на `subscribed?`, так лишний запрос получается.

2016-10-14 16:07 UTC, palkan commented on app/jobs/daily_digest_job.rb
> +    User.find_each do |user|
Такой момент: сейчас мы для каждого пользователя заново выгружаем один и тот же список вопросов. Но можно же сначала выгрузить его, а потом отправлять всем.

2016-10-14 17:01 UTC, Arkweid commented on app/models/user.rb
> +    subscriptions.where(question: question).delete_all if subscribed?(question)
Хм, точно.

2016-10-14 17:01 UTC, Arkweid commented on app/jobs/daily_digest_job.rb
> +    User.find_each do |user|
Теперь вижу что много лишних действий.

2016-10-14 17:03 UTC, Arkweid commented on app/models/question.rb
> +  scope :from_yesterday, -> { where(created_at: (Time.now - 1.day).beginning_of_day.utc..(Time.now - 1.day).end_of_day.utc) }
Как то перемудрил по итогу.

2016-10-15 17:31 UTC, palkan requested changes

2016-10-15 17:31 UTC, palkan commented on app/jobs/daily_digest_job.rb
> +    DailyMailer.questions = Question.from_yesterday
Нужны тесты на этот функционал, как в тестах для воркера, так и в тестах для мейлера (нужно проверить, что вопросы есть в теле письма);

2016-10-16 16:53 UTC, Arkweid commented on app/jobs/daily_digest_job.rb
> +    DailyMailer.questions = Question.from_yesterday
Добавил тест на скоуп '.from_yesterday' модели Question.
Изменил метод digest, сделал его более ясным. Теперь он принимает не только юзера, но и список вопросов.
Добавил тесты для мейлера. Проверяю что нужные вопросы находятся в теле письма.

2016-10-17 18:29 UTC, merged